export const GET_INPUT_VALUE = "GET_INPUT_VALUE";
export const ADD_INPUT_VALUE = "ADD_INPUT_VALUE";
export const DELETE_INPUT_VALUE = "DELETE_INPUT_VALUE";
export const SELECT_INPUT_VALUE = "SELECT_INPUT_VALUE";
export const INIT_INPUT_VALUE = "INIT_INPUT_VALUE";
export const CLICK_LIST = "CLICK_LIST";
export const UPDATE_LIST_VALUE = "UPDATE_LIST_VALUE";
export const SAVE_LIST_VALUE = "SAVE_LIST_VALUE";
